name: ci

on:
  push:
    branches:
      - main

jobs:
  buildx:
     runs-on: ubuntu-latest
     steps:
       - name: Checkout repository
         uses: actions/checkout@v3
       - name: Get current date
         id: date
         run: echo "::set-output name=today::$(date +'%Y%m%d%H%M')"
         shell: bash
       - name: Set up QEMU
         uses: docker/setup-qemu-action@v2
         with:
          platforms: 'arm64,arm'
       - name: Set up Docker Buildx
         uses: docker/setup-buildx-action@v2
       - name: cd
         run: |
          docker build --no-cache -t  messaging-topology-operator:v1 .
          docker save -o messaging-topology-operator.tar messaging-topology-operator:v1 
          ls -allh
       - name: Create Release
         id: create_release
         uses: actions/create-release@v1
         env:
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
         with:
           tag_name: v0.0.${{ steps.date.outputs.today }}
           release_name: Release v0.0.${{ steps.date.outputs.today }}
           draft: false
           prerelease: false

       - name: Upload Release Asset
         id: upload-release-asset 
         uses: actions/upload-release-asset@v1
         env:
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
         with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: messaging-topology-operator.tar
          asset_name: messaging-topology-operator.tar
          asset_content_type: application/zip
